"""
VSDL Python Compiler - Ansible Playbook Generator
Generates Ansible playbooks from VSDL AST.
Uses Software Registry for intelligent software installation.
"""

from typing import Dict, List, Optional
from jinja2 import Template
from ..ast_nodes import Scenario, NodeDefinition, SoftwareDependency
from ...software_registry import SoftwareRegistry, LLMInstallGenerator


# ============================================================================
# Software Package Mapping
# Maps VSDL software names to actual package names for different package managers
# ============================================================================

# APT package name mapping (Ubuntu/Debian)
APT_PACKAGE_MAPPING = {
    # Java runtimes and JDKs
    'java': 'openjdk-11-jdk',
    'jdk': 'openjdk-11-jdk',
    'openjdk': 'openjdk-11-jdk',
    'openjdk-8': 'openjdk-8-jdk',
    'openjdk-11': 'openjdk-11-jdk',
    'openjdk-17': 'openjdk-17-jdk',

    # Web servers
    'nginx': 'nginx',
    'apache': 'apache2',
    'apache2': 'apache2',
    'httpd': 'apache2',
    'tomcat': 'tomcat9',
    'apache-tomcat': 'tomcat9',

    # Databases
    'mysql': 'mysql-server',
    'mariadb': 'mariadb-server',
    'postgresql': 'postgresql',
    'postgres': 'postgresql',
    'mongodb': 'mongodb',
    'redis': 'redis-server',

    # Languages and runtimes
    'python': 'python3',
    'python3': 'python3',
    'python3-pip': 'python3-pip',
    'pip': 'python3-pip',
    'nodejs': 'nodejs',
    'node': 'nodejs',
    'npm': 'npm',
    'php': 'php',
    'ruby': 'ruby',
    'golang': 'golang-go',
    'go': 'golang-go',
    'rust': 'rustc',

    # Dev tools
    'docker': 'docker.io',
    'git': 'git',
    'curl': 'curl',
    'wget': 'wget',
    'vim': 'vim',
    'nano': 'nano',

    # Security tools
    'nmap': 'nmap',
    'wireshark': 'wireshark',
    'metasploit': 'metasploit-framework',
    'burpsuite': 'burpsuite',

    # Other common packages
    'ssh': 'openssh-server',
    'openssh': 'openssh-server',
    'ftp': 'vsftpd',
    'vsftpd': 'vsftpd',
    'samba': 'samba',
    'dns': 'bind9',
    'bind': 'bind9',
}

# Software that requires special installation methods (not apt)
SPECIAL_SOFTWARE = {
    'bonitasoft': {
        'method': 'download_war',
        'download_url': 'https://github.com/bonitasoft/bonita-engine/releases/download/{version}/bonita-engine-{version}.war',
        'requires': ['java', 'tomcat'],
        'default_version': '7.13.0',
    },
    'jenkins': {
        'method': 'apt_key',
        'key_url': 'https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key',
        'repo': 'deb https://pkg.jenkins.io/debian-stable binary/',
        'package': 'jenkins',
    },
    'docker-compose': {
        'method': 'pip',
        'package': 'docker-compose',
    },
}


# Ansible templates
# OS type to default username mapping
# Note: Windows uses 'Admin' for the SSH-enabled win10-ssh image
OS_USER_MAPPING = {
    'ubuntu': 'ubuntu',
    'ubuntu20': 'ubuntu',
    'ubuntu18': 'ubuntu',
    'ubuntu16': 'ubuntu',
    'ubuntu24': 'ubuntu',
    'kali': 'kali',
    'debian': 'debian',
    'centos': 'centos',
    'centos-7': 'centos',
    'openeuler': 'root',
    'openeuler20.03': 'root',
    'rhel': 'cloud-user',
    'fedora': 'fedora',
    'windows': 'Admin',
    'win': 'Admin',
    'win10': 'Admin',
    'win10-ssh': 'Admin',
    'win2003': 'Admin',
    'win2008': 'Admin',
    'win2012': 'Admin',
    'win2016': 'Admin',
    'win2019': 'Admin',
    'windows10': 'Admin',
    'windows_server': 'Admin',
}


def is_windows_os(os_image: Optional[str]) -> bool:
    """Check if the OS is Windows based on image name."""
    if not os_image:
        return False
    os_lower = os_image.lower().strip()
    # Check exact match or partial match for Windows variants
    return os_lower in OS_USER_MAPPING and os_lower.startswith('win') or 'win' in os_lower


def get_ansible_user(os_image: Optional[str]) -> str:
    """Get the appropriate Ansible username for the OS."""
    if not os_image:
        return 'ubuntu'
    os_lower = os_image.lower().strip()
    # Direct lookup
    if os_lower in OS_USER_MAPPING:
        return OS_USER_MAPPING[os_lower]
    # Check for Windows variants
    if 'win' in os_lower:
        return 'Admin'
    # Default to ubuntu
    return 'ubuntu'

INVENTORY_TEMPLATE = """
# Ansible inventory generated by VSDL Python Compiler
# Scenario: {{ scenario.name }}

[all:vars]
ansible_port = 22
ansible_ssh_private_key_file = ~/.ssh/vsdl_key
ansible_python_interpreter = /usr/bin/python3
ansible_ssh_common_args = -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null

{% for group_name, nodes in groups.items() %}
[{{ group_name }}]
{% for node in nodes %}
{{ node.name }} ansible_host={{ node.ip }} ansible_port=22 ansible_user={{ node.ansible_user | default('ubuntu') }}
{% endfor %}
{% endfor %}

{% if vulnerabilities %}
# Vulnerability groups
{% for vuln in vulnerabilities %}
[vulnerability_{{ vuln.name }}]
{% for node_name in vuln_nodes.get(vuln.name, []) %}
{{ node_name }}
{% endfor %}
{% endfor %}
{% endif %}
"""

SITE_PLAYBOOK_TEMPLATE = """
---
# Main Ansible playbook generated by VSDL Python Compiler
# Scenario: {{ scenario.name }}
# Duration: {{ scenario.duration }} TTU

- name: Configure all nodes
  hosts: all
  become: yes
  roles:
    - common

{% for node in nodes %}
- name: Configure {{ node.name }}
  hosts: {{ node.name }}
  become: yes
  roles:
    {% for sw in node.software_mounts %}
    - {{ sw.name | lower }}
    {% endfor %}
  tasks:
    - name: Display node info
      debug:
        msg: "Node {{ node.name }} - OS: {{ node.os_image }}, RAM: {{ node.ram_value }}GB, vCPU: {{ node.vcpu }}"

    {% if node.software_mounts %}
    - name: Install software packages
      include_tasks: tasks/install_software.yml
      loop:
        {% for sw in node.software_mounts %}
        - name: "{{ sw.name }}"
          version: "{{ sw.version or 'latest' }}"
        {% endfor %}
      loop_control:
        loop_var: software_item
    {% endif %}
{% endfor %}

{% if vulnerabilities %}
# Vulnerability topology tasks
- name: Configure vulnerability environment
  hosts: all
  become: yes
  tasks:
    - name: Create vulnerability markers directory
      file:
        path: /opt/vsdl/vulnerabilities
        state: directory
        mode: '0755'

    {% for vuln in vulnerabilities %}
    - name: Mark vulnerability {{ vuln.name }}
      copy:
        dest: /opt/vsdl/vulnerabilities/{{ vuln.name }}
        content: |
          Vulnerability: {{ vuln.name }}
          CVE: {{ vuln.cve_id or 'N/A' }}
          Software: {{ vuln.vulnerable_software or 'N/A' }}
          Version: {{ vuln.vulnerable_version or 'N/A' }}
          Host: {{ vuln.hosted_on_node or 'N/A' }}
          {% if vuln.requires_vulnerabilities %}
          Requires: {{ vuln.requires_vulnerabilities | join(', ') }}
          {% endif %}
          {% if vuln.triggers_vulnerabilities %}
          Triggers: {{ vuln.triggers_vulnerabilities | join(', ') }}
          {% endif %}
        mode: '0644'
      when: inventory_hostname == "{{ vuln.hosted_on_node }}"
    {% endfor %}
{% endif %}
"""

COMMON_ROLES_MAIN_TEMPLATE = """---
# Common role - base configuration for all nodes
# Generated by VSDL Python Compiler

- name: Update apt cache
  apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install common packages
  apt:
    name:
      - curl
      - wget
      - git
      - vim
      - htop
      - net-tools
      - python3-pip
    state: present

- name: Create vsdl user
  user:
    name: vsdl
    shell: /bin/bash
    groups: sudo
    append: true

- name: Create VSDL root directory
  file:
    path: /opt/vsdl
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create VSDL logs directory
  file:
    path: /opt/vsdl/logs
    state: directory
    mode: "0755"
    owner: root
    group: root

- name: Create VSDL vulnerabilities directory
  file:
    path: /opt/vsdl/vulnerabilities
    state: directory
    mode: "0755"
    owner: root
    group: root
"""

INSTALL_SOFTWARE_TASK_TEMPLATE = """
---
# Generic software installation task
# Uses package name mapping to resolve correct apt package names
# Note: software_item is passed via loop_control from the parent playbook

- name: Resolve package name
  set_fact:
    resolved_package_name: "{{ '%s' | format(software_item.name) }}"
  # Package name resolution is handled during playbook generation

- name: Check if special installation is required
  set_fact:
    is_special_package: false

- name: Install package via apt
  apt:
    name: "{{ resolved_package_name }}"
    state: present
    update_cache: true
  when: not is_special_package and software_item.version == 'latest'
  ignore_errors: yes
  register: apt_install_result

- name: Install specific version via apt
  apt:
    name: "{{ resolved_package_name }}={{ software_item.version }}"
    state: present
    update_cache: true
  when: not is_special_package and software_item.version != 'latest'
  ignore_errors: yes
  register: apt_version_install_result

- name: Check if installation was successful
  command: "which {{ software_item.name }}"
  register: software_check
  changed_when: false
  ignore_errors: yes
  when: not is_special_package

- name: Log installation status
  debug:
    msg: |
      Software {{ software_item.name }}:
      - Resolved package: {{ resolved_package_name }}
      - Installation result: {{ 'SUCCESS' if (software_check.rc | default(1)) == 0 else 'NEEDS MANUAL INSTALL' }}
      {% if software_item.version and software_item.version != 'latest' %}
      - Requested version: {{ software_item.version }}
      {% endif %}
"""

# Template for software roles with proper package name resolution
SOFTWARE_ROLE_TEMPLATE = """---
# Role: {{ software.name }}
# Generated by VSDL Python Compiler
# Package mapping: {{ software.name }} -> {{ apt_package }}

- name: Install {{ software.name }}
  block:
    - name: Install {{ software.name }} via apt
      apt:
        name: "{{ apt_package }}"
        state: present
        update_cache: true
{% if software.version and software.version != 'latest' %}
    - name: Install specific version {{ software.version }}
      apt:
        name: "{{ apt_package }}={{ software.version }}"
        state: present
        update_cache: true
      ignore_errors: yes
{% endif %}
      ignore_errors: yes
      register: apt_result

    - name: Check if {{ software.name }} was installed
      shell: "dpkg -l | grep {{ apt_package.split('=')[0] }} || which {{ software.name }}"
      register: install_check
      changed_when: false
      ignore_errors: yes

    - name: Installation status
      debug:
        msg: |
          {{ software.name }} installation:
          - APT package: {{ apt_package }}
          - Status: {{ 'INSTALLED' if install_check.rc == 0 else 'NEEDS MANUAL SETUP' }}
{% if software.config %}
          - Configuration: {{ software.config | to_json }}
{% endif %}

{% if software.dependencies %}
    - name: Install dependencies for {{ software.name }}
      apt:
        name:
{% for dep in software.dependencies %}
          - {{ APT_PACKAGE_MAPPING.get(dep.lower(), dep) }}
{% endfor %}
        state: present
        update_cache: true
      ignore_errors: yes
{% endif %}

{% if software.config %}
    - name: Create configuration directory
      file:
        path: /etc/{{ software.name | lower }}
        state: directory
        mode: "0755"

    - name: Apply configuration for {{ software.name }}
      copy:
        dest: /etc/{{ software.name | lower }}/vsdl_config.conf
        content: |
{% for key, value in software.config.items() %}
          {{ key }}={{ value }}
{% endfor %}
        mode: "0644"
{% endif %}
"""


class AnsibleGenerator:
    """
    Generates Ansible playbooks from VSDL AST.
    Uses Software Registry for intelligent software installation.
    """

    def __init__(self, llm_client=None):
        self.inventory_template = Template(INVENTORY_TEMPLATE)
        self.site_template = Template(SITE_PLAYBOOK_TEMPLATE)
        self.common_roles_template = Template(COMMON_ROLES_MAIN_TEMPLATE)
        # Initialize software registry and LLM generator
        self.software_registry = SoftwareRegistry()
        self.llm_generator = LLMInstallGenerator(llm_client)
        # Note: INSTALL_SOFTWARE_TASK_TEMPLATE is used directly as a raw string

    def generate(self, scenario: Scenario, node_ips: Optional[Dict[str, str]] = None) -> Dict[str, str]:
        """
        Generate Ansible files from a VSDL scenario.

        Args:
            scenario: The VSDL scenario AST
            node_ips: Optional mapping of node names to IP addresses

        Returns:
            Dict mapping filename to content
        """
        if not node_ips:
            node_ips = self._extract_node_ips(scenario)

        # Build groups
        groups = self._build_groups(scenario, node_ips)

        # Build vulnerability-to-nodes mapping
        vuln_nodes = {}
        for vuln in scenario.vulnerabilities:
            if vuln.hosted_on_node:
                if vuln.name not in vuln_nodes:
                    vuln_nodes[vuln.name] = []
                vuln_nodes[vuln.name].append(vuln.hosted_on_node)

        # Generate files
        files = {
            'inventory.ini': self._generate_inventory(scenario, groups, vuln_nodes, node_ips),
            'site.yml': self._generate_site_playbook(scenario, vuln_nodes),
            'roles/common/tasks/main.yml': self._generate_common_role(),
            'tasks/install_software.yml': self._generate_install_software_task(),
        }

        # Generate role-specific playbooks for each software
        software_roles = self._generate_software_roles(scenario)
        for role_path, content in software_roles.items():
            files[role_path] = content

        return files

    def _extract_node_ips(self, scenario: Scenario) -> Dict[str, str]:
        """Extract node IPs from network definitions"""
        node_ips = {}

        for network in scenario.networks:
            for conn in network.connections:
                # Check if it's a node (not another network)
                if conn.node_name in [n.name for n in scenario.nodes]:
                    if conn.ip_address:
                        node_ips[conn.node_name] = conn.ip_address

        return node_ips

    def _build_groups(self, scenario: Scenario, node_ips: Dict[str, str]) -> Dict[str, List[Dict]]:
        """Build inventory groups with OS-specific usernames"""
        groups = {
            'all': []
        }

        # Build node list with OS-specific usernames
        for node in scenario.nodes:
            node_ip = node_ips.get(node.name, 'unknown')
            os_type = (node.os_image or 'ubuntu').lower()
            # Get username based on OS type, default to 'ubuntu'
            ansible_user = get_ansible_user(node.os_image)

            node_info = {
                'name': node.name,
                'ip': node_ip,
                'os': os_type,
                'ansible_user': ansible_user
            }
            groups['all'].append(node_info)

        # Group by OS
        os_groups = {}
        for node in scenario.nodes:
            os_name = (node.os_image or 'unknown').lower()
            if os_name not in os_groups:
                os_groups[os_name] = []

            node_ip = node_ips.get(node.name, 'unknown')
            ansible_user = get_ansible_user(node.os_image)

            os_groups[os_name].append({
                'name': node.name,
                'ip': node_ip,
                'os': os_name,
                'ansible_user': ansible_user
            })
        groups.update(os_groups)

        # Group by vulnerability
        for vuln in scenario.vulnerabilities:
            group_name = f'vulnerability_{vuln.name}'
            if vuln.hosted_on_node:
                # Find the node to get its OS type
                node_obj = next((n for n in scenario.nodes if n.name == vuln.hosted_on_node), None)
                os_type = (node_obj.os_image or 'ubuntu').lower() if node_obj else 'ubuntu'
                ansible_user = get_ansible_user(node_obj.os_image) if node_obj else 'ubuntu'

                ip = node_ips.get(vuln.hosted_on_node, 'unknown')
                groups[group_name] = [{
                    'name': vuln.hosted_on_node,
                    'ip': ip,
                    'os': os_type,
                    'ansible_user': ansible_user
                }]

        return groups

    def _generate_inventory(self, scenario: Scenario, groups: Dict,
                            vuln_nodes: Dict, node_ips: Dict[str, str]) -> str:
        """Generate inventory.ini content"""
        return self.inventory_template.render(
            scenario=scenario,
            groups=groups,
            vulnerabilities=scenario.vulnerabilities,
            vuln_nodes=vuln_nodes
        )

    def _generate_site_playbook(self, scenario: Scenario, vuln_nodes: Dict) -> str:
        """Generate site.yml content"""
        # Filter nodes that have IPs
        nodes_with_ips = []
        for node in scenario.nodes:
            nodes_with_ips.append(node)

        return self.site_template.render(
            scenario=scenario,
            nodes=nodes_with_ips,
            vulnerabilities=scenario.vulnerabilities,
            vuln_nodes=vuln_nodes
        )

    def _generate_common_role(self) -> str:
        """Generate common role tasks"""
        return self.common_roles_template.render()

    def _generate_install_software_task(self) -> str:
        """Generate software installation task"""
        # Return raw content - software_item is a runtime variable in Ansible
        # Do not use Jinja2 render() as it would try to resolve software_item
        return INSTALL_SOFTWARE_TASK_TEMPLATE

    def _generate_software_roles(self, scenario: Scenario) -> Dict[str, str]:
        """Generate role-specific playbooks for software"""
        roles = {}
        generated_software = set()

        for node in scenario.nodes:
            for sw in node.software_mounts:
                sw_name = sw.name.lower()
                if sw_name in generated_software:
                    continue
                generated_software.add(sw_name)

                # Generate a minimal role
                roles[f'roles/{sw_name}/tasks/main.yml'] = self._generate_software_role(sw)

        return roles

    def _generate_software_role(self, software: SoftwareDependency) -> str:
        """Generate a role for a specific software using the knowledge base"""
        sw_name = software.name.lower()

        # Query the software registry
        sw_info = self.software_registry.get_install_info(sw_name, software.version)

        # If not found in knowledge base, try LLM generation
        if sw_info.get('needs_llm_generation'):
            sw_info = self.llm_generator.generate_install_script(
                software_name=sw_name,
                version=software.version,
                os_type="ubuntu",
                offline_mode=False
            )

        # Generate role content based on install type
        install_type = sw_info.get('install_type', 'apt')
        package = sw_info.get('package', sw_name)
        verify_cmd = sw_info.get('verify_cmd', f"which {sw_name}")
        install_script = sw_info.get('install_script')
        dependencies = sw_info.get('dependencies', [])
        note = sw_info.get('note', '')
        generated_by_llm = sw_info.get('generated_by_llm', False)

        role_content = f"""---
# Role: {software.name}
# Generated by VSDL Python Compiler
# Install type: {install_type}
# Package mapping: {software.name} -> {package}
"""

        if generated_by_llm:
            role_content += "# Note: Generated by LLM (not in knowledge base)\n"

        role_content += f"""
- name: Install {software.name}
  block:
"""

        if install_type == 'apt':
            role_content += self._generate_apt_tasks(software.name, package, software.version)
        elif install_type == 'script' and install_script:
            role_content += self._generate_script_tasks(software.name, install_script)
        elif install_type == 'manual':
            role_content += self._generate_manual_tasks(software.name, note or "Requires manual installation")
        else:
            # Fallback to apt
            role_content += self._generate_apt_tasks(software.name, package, software.version)

        role_content += f"""
    - name: Verify {software.name} installation
      command: "{verify_cmd}"
      register: install_check
      changed_when: false
      ignore_errors: yes

    - name: Installation status
      debug:
        msg: |
          {software.name} installation:
          - Install type: {install_type}
          - Package: {package}
          - Status: {{ 'INSTALLED' if install_check.rc == 0 else 'NEEDS MANUAL SETUP' }}
"""

        # Add dependencies if any
        if dependencies:
            role_content += """
    - name: Install dependencies
      apt:
        name:
"""
            for dep in dependencies:
                dep_info = self.software_registry.get_install_info(dep)
                dep_package = dep_info.get('package', dep)
                role_content += f'          - {dep_package}\n'

        # Add configuration tasks
        if software.config:
            role_content += f"""
    - name: Create configuration directory
      file:
        path: /etc/{sw_name}
        state: directory
        mode: '0755'

    - name: Apply configuration
      copy:
        dest: /etc/{sw_name}/vsdl_config.conf
        content: |
"""
            for key, value in software.config.items():
                role_content += f'          {key}={value}\n'

        return role_content

    def _generate_apt_tasks(self, name: str, package: str, version: str = None) -> str:
        """Generate apt installation tasks"""
        tasks = f"""    - name: Install {name} via apt
      apt:
        name: "{package}"
        state: present
        update_cache: true
      ignore_errors: yes
      register: apt_result
"""
        if version and version != 'latest':
            tasks += f"""
    - name: Install specific version {version}
      apt:
        name: "{package}={version}"
        state: present
        update_cache: true
      ignore_errors: yes
"""
        return tasks

    def _generate_script_tasks(self, name: str, script: str) -> str:
        """Generate script-based installation tasks"""
        # Indent the script properly for YAML
        indented_script = '\n'.join(' ' * 8 + line for line in script.strip().split('\n'))
        return f"""    - name: Install {name} via script
      shell: |
{indented_script}
      args:
        executable: /bin/bash
      ignore_errors: yes
"""

    def _generate_manual_tasks(self, name: str, note: str) -> str:
        """Generate manual installation notice"""
        return f"""    - name: {name} requires manual installation
      debug:
        msg: |
          Software: {name}
          Note: {note}
          Please install manually or prepare offline resources.
"""