"""
LLM Install Script Generator
当知识库中没有找到软件时，使用 LLM 生成安装脚本
"""

import os
import json
from typing import Dict, Optional, Any


class LLMInstallGenerator:
    """
    LLM 安装脚本生成器

    当知识库中没有找到软件时，调用 LLM 生成安装脚本
    """

    def __init__(self, llm_client=None):
        """
        初始化生成器

        Args:
            llm_client: LLM 客户端（如 OpenAI、Claude 等）
        """
        self.llm_client = llm_client

    def generate_install_script(
        self,
        software_name: str,
        version: Optional[str] = None,
        os_type: str = "ubuntu",
        offline_mode: bool = False
    ) -> Dict[str, Any]:
        """
        生成软件安装脚本

        Args:
            software_name: 软件名称
            version: 版本号
            os_type: 目标操作系统
            offline_mode: 是否离线模式

        Returns:
            包含安装信息的字典
        """
        # 构建 prompt
        prompt = self._build_prompt(software_name, version, os_type, offline_mode)

        # 调用 LLM
        if self.llm_client:
            try:
                response = self._call_llm(prompt)
                return self._parse_llm_response(response, software_name)
            except Exception as e:
                # LLM 调用失败，返回默认的 apt 尝试
                return self._get_fallback_response(software_name, version, str(e))
        else:
            # 没有配置 LLM 客户端，返回默认尝试
            return self._get_fallback_response(software_name, version, "No LLM client configured")

    def _build_prompt(
        self,
        software_name: str,
        version: Optional[str],
        os_type: str,
        offline_mode: bool
    ) -> str:
        """构建 LLM prompt"""
        prompt = f"""Generate an installation script for the following software:

Software: {software_name}
Version: {version or 'latest'}
Target OS: {os_type}
Offline Mode: {offline_mode}

Requirements:
1. Use bash shell script
2. Use apt package manager for Ubuntu/Debian systems
3. If offline mode is True, only use apt install (no external downloads)
4. Include error handling with 'set -e' or '|| exit 1'
5. The script should be idempotent (safe to run multiple times)

Return a JSON object with the following structure:
{{
    "install_type": "apt|script|manual",
    "package": "apt-package-name (if type is apt)",
    "install_script": "full bash script (if type is script)",
    "verify_cmd": "command to verify installation",
    "dependencies": ["list", "of", "dependencies"],
    "offline_available": true/false,
    "note": "any special notes"
}}

Only return the JSON object, no other text.
"""
        return prompt

    def _call_llm(self, prompt: str) -> str:
        """调用 LLM"""
        # 这里需要根据实际的 LLM 客户端进行调整
        # 支持多种 LLM 客户端接口

        if hasattr(self.llm_client, 'chat'):
            # OpenAI style
            response = self.llm_client.chat.completions.create(
                model="gpt-4",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3
            )
            return response.choices[0].message.content

        elif hasattr(self.llm_client, 'messages'):
            # Anthropic/Claude style
            response = self.llm_client.messages.create(
                model="claude-3-sonnet-20240229",
                max_tokens=1024,
                messages=[{"role": "user", "content": prompt}]
            )
            return response.content[0].text

        elif callable(self.llm_client):
            # Generic callable
            return self.llm_client(prompt)

        else:
            raise ValueError("Unsupported LLM client type")

    def _parse_llm_response(self, response: str, software_name: str) -> Dict[str, Any]:
        """解析 LLM 响应"""
        try:
            # 尝试提取 JSON
            # 有时 LLM 会返回带有 ```json 标记的内容
            json_str = response.strip()
            if "```json" in json_str:
                json_str = json_str.split("```json")[1].split("```")[0].strip()
            elif "```" in json_str:
                json_str = json_str.split("```")[1].split("```")[0].strip()

            data = json.loads(json_str)

            return {
                'found': True,
                'generated_by_llm': True,
                'name': software_name,
                'install_type': data.get('install_type', 'apt'),
                'package': data.get('package', software_name.lower()),
                'install_script': data.get('install_script'),
                'verify_cmd': data.get('verify_cmd', f"which {software_name.lower()}"),
                'dependencies': data.get('dependencies', []),
                'offline_available': data.get('offline_available', False),
                'note': data.get('note', 'Generated by LLM')
            }
        except json.JSONDecodeError:
            # JSON 解析失败，返回默认
            return self._get_fallback_response(software_name, None, "Failed to parse LLM response")

    def _get_fallback_response(
        self,
        software_name: str,
        version: Optional[str],
        error: str
    ) -> Dict[str, Any]:
        """获取回退响应（默认尝试 apt 安装）"""
        return {
            'found': False,
            'generated_by_llm': False,
            'name': software_name,
            'install_type': 'apt',
            'package': software_name.lower(),
            'install_script': None,
            'verify_cmd': f"which {software_name.lower()}",
            'dependencies': [],
            'offline_available': True,
            'note': f"LLM generation failed: {error}. Will try apt install as fallback."
        }


def generate_ansible_install_task(software_info: Dict[str, Any]) -> str:
    """
    根据软件信息生成 Ansible 安装任务 YAML

    Args:
        software_info: 软件安装信息字典

    Returns:
        Ansible task YAML 字符串
    """
    install_type = software_info.get('install_type', 'apt')
    name = software_info.get('name', 'unknown')
    package = software_info.get('package', name.lower())
    verify_cmd = software_info.get('verify_cmd', f"which {name.lower()}")
    install_script = software_info.get('install_script')

    if install_type == 'apt':
        return f"""
- name: Install {name} via apt
  apt:
    name: {package}
    state: present
    update_cache: true
  ignore_errors: yes

- name: Verify {name} installation
  command: "{verify_cmd}"
  register: {name}_check
  changed_when: false
  ignore_errors: yes
"""

    elif install_type == 'script' and install_script:
        return f"""
- name: Install {name} via script
  shell: |
    {install_script}
  args:
    executable: /bin/bash
  ignore_errors: yes

- name: Verify {name} installation
  command: "{verify_cmd}"
  register: {name}_check
  changed_when: false
  ignore_errors: yes
"""

    elif install_type == 'manual':
        note = software_info.get('note', 'Requires manual installation')
        return f"""
- name: {name} requires manual installation
  debug:
    msg: |
      Software: {name}
      Note: {note}
      Please install manually or prepare offline resources.
"""

    else:
        # 默认 apt 尝试
        return f"""
- name: Try to install {name} via apt
  apt:
    name: {package}
    state: present
    update_cache: true
  ignore_errors: yes

- name: Check {name} installation
  command: "{verify_cmd}"
  register: {name}_check
  changed_when: false
  ignore_errors: yes
"""