from flask import Blueprint, jsonify, request, current_app
from app.tasks import process_scenario_file_task
from app.utils.response import Response, ErrorCode
import os
import time
import traceback


# Create target range blueprint
target_range_bp = Blueprint('target_range', __name__)

# API for generating target range content
@target_range_bp.route('/generate', methods=['POST'])
def generate_target():
    """
    Asynchronously generate target range content based on an uploaded file.
    This is initiated by guan-ji and will report back via a callback.
    ---
    tags:
      - Target Range Generation
    summary: Asynchronously generate target range content
    description: >
      Initiates an asynchronous job to generate a target range environment based on the provided file.
      The caller must provide a taskId for tracking and a callbackUrl for completion notification.
    consumes:
      - multipart/form-data
    parameters:
      - name: file
        in: formData
        type: file
        required: true
        description: The scenario definition file (e.g., zip, yaml).
      - name: taskId
        in: formData
        type: string
        required: true
        description: The unique ID generated by the calling service (guan-ji) to track the task.
      - name: callbackUrl
        in: formData
        type: string
        required: true
        description: The URL that this service will POST the result to upon completion.
    responses:
      202:
        description: Task accepted for processing.
      400:
        description: Invalid or missing parameters.
    """
    try:
        current_app.logger.info('Received request to generate target range.')
        
        # 调试信息：记录请求详情
        current_app.logger.info(f'请求方法: {request.method}')
        current_app.logger.info(f'请求头: {dict(request.headers)}')
        current_app.logger.info(f'表单数据: {dict(request.form)}')
        current_app.logger.info(f'文件数量: {len(request.files)}')
        
        # Check for required form fields
        if 'file' not in request.files:
            current_app.logger.error('请求中缺少文件')
            return Response.error(ErrorCode.PARAM_ERROR, "Missing 'file' in request"), 400
        
        scenario_file = request.files['file']
        task_id = request.form.get('taskId')
        callback_url = request.form.get('callbackUrl')
        
        # 调试信息：记录文件信息
        current_app.logger.info(f'文件名: {scenario_file.filename}')
        current_app.logger.info(f'文件类型: {scenario_file.content_type}')
        current_app.logger.info(f'任务ID: {task_id}')
        current_app.logger.info(f'回调URL: {callback_url}')

        if not all([task_id, callback_url]):
            current_app.logger.error('缺少任务ID或回调URL')
            return Response.error(ErrorCode.PARAM_ERROR, "Missing 'taskId' or 'callbackUrl' in form data"), 400

        # Save the uploaded file to a temporary location for the background task
        temp_dir = os.path.join('/tmp', 'crcg_uploads')
        os.makedirs(temp_dir, exist_ok=True)
        file_path = os.path.join(temp_dir, f"{task_id}_{int(time.time())}_{scenario_file.filename}")
        scenario_file.save(file_path)
        
        # 调试信息：记录文件保存路径
        current_app.logger.info(f'文件保存路径: {file_path}')
        current_app.logger.info(f'文件大小: {os.path.getsize(file_path)} 字节')
        current_app.logger.info(f'文件存在: {os.path.exists(file_path)}')
        
        # 调试信息：环境变量
        current_app.logger.info(f'HF_HOME环境变量: {os.environ.get("HF_HOME", "Not set")}')
        current_app.logger.info(f'HF_HUB_LOCAL_DIR环境变量: {os.environ.get("HF_HUB_LOCAL_DIR", "Not set")}')
        current_app.logger.info(f'UNSTRUCTURED_LOCAL_INFERENCE环境变量: {os.environ.get("UNSTRUCTURED_LOCAL_INFERENCE", "Not set")}')

        # Launch the background task with the file path and callback URL
        task = process_scenario_file_task.apply_async(
            args=[file_path, callback_url],
            task_id=task_id
        )
        
        current_app.logger.info(f"Task for taskId {task.id} has been dispatched.")
        
        return Response.success({
            'message': 'Target generation task accepted.',
            'taskId': task.id
        }), 202
        
    except Exception as e:
        current_app.logger.exception('Unexpected error occurred while initiating target generation.')
        
        # 调试信息：详细错误追踪
        current_app.logger.error(f'详细错误堆栈: {traceback.format_exc()}')
        
        return Response.error(ErrorCode.SERVER_ERROR, f"Error initiating target generation: {str(e)}"), 500
